### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by nickalaskreynolds** [dashwav/yin-bot#37] opened 2019-02-09 15:30 UTC
Deleting or removing perms for one log channel breaks posting for all logs.

Say you do `logging enable` for channels A and B
Then you either delete the channel or remove her read perms for channel B.
This will disable her output to channel A and throw a FORBIDDEN error in the console.
If you just remove read perms it is easy, just reenable them, but if you delete the channel, you have to remove it manually. 

Probably should just wrap this into a nicer function to handle sending to only some of the channels. Also, maybe add the ability in logging/vclogs disable/enable to specify the channel.

**Comment by dashwav** [comment] 2019-05-07 04:04
Actually closing since it is a duplicate of #41

**Closed by dashwav** 2019-05-07 04:04 UTC
Labels: bug, good first issue, short
